# Uncomment the next line to define a global platform for your project
platform :ios, '8.1.2'
target 'wine' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wine

  target 'wineTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


