# Uncomment the next line to define a global platform for your project
platform :ios, '8.1.2'
target 'wine' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wine

  target 'wine-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'wineTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'wine-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wine-tvOS

  target 'wine-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
